services:
  app:
    image: hnkhang/lpr:app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    volumes:
      - .:/LPR

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    depends_on:
      - app
    environment:
      - NGROK_AUTHTOKEN=2do0dydLRxCpwbVvTgbKrW55YoO_7vTMLQuBbr1CYQ8URTAzX
    command: ngrok http app:8000
